backend:
  name: git-gateway
  branch: main # Cambia a la rama que usas (por ejemplo, "main" o "master")

media_folder: "assets" # Carpeta donde se guardarán las imágenes
public_folder: "/assets" # Carpeta pública para imágenes

collections:
  - name: "noticias"          # Identificador interno de la colección
    label: "Noticias"         # Nombre visible en el CMS
    folder: "content/noticias" # Carpeta donde se guardarán las tarjetas
    create: true              # Permitir al usuario crear nuevas tarjetas
    fields:                   # Campos de cada tarjeta
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
